# Generated by Django 5.1.6 on 2025-03-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoorders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
