# Generated by Django 5.1.6 on 2025-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecousers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
